server:
  port: 9999

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/wanted-h2
    username: sa
    password: 1234
#  datasource:
#    url: jdbc:mysql://localhost:3307/recruitment?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

springdoc:
  use-fqn: true
