server:
  port: 9999

spring:
  config:
    import: application-secret.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

springdoc:
  use-fqn: true
