server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/recruitment?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

springdoc:
  use-fqn: true
